customer/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='custome_index'),
    path('house/', housedesigns, name='custome_housedesigns'),
    path('house/<int:id>', housedesignsdetails, name='custome_housedesignsdetails'),

    path('booknow/<int:id>', booknow, name='custome_booknow'),
    path('orders/', my_orders, name='custome_my_orders'),
    path('orders/delete/<int:id>', delete_order, name='custome_delete_order'),
    path('project/', manage_project, name='custome_manage_project'),
    path('project/create/', add_project, name='custome_add_project'),
    path('project/edit/<int:id>', edit_project, name='custome_edit_project'),
    path('project/remove/<int:id>', delete_project, name='custome_delete_project'),
    path('complaint/', add_compalints, name='custome_add_compalints'),

]

srs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('admin.urls')),
    path('accounts/', include('accounts.urls')),
    path('engineer/', include('engineer.urls')),
    path('', include('customer.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin/models.py
from django.db import models
from accounts.models import User, SiteEngineer
from datetime import date
from customer.models import Project

# Create your models here.

class Equipment(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    type_choices = [
        ('excavator', 'Excavator'),
        ('bulldozer', 'Bulldozer'),
        ('crane', 'Crane'),
        ('loader', 'Loader')
    ]
    equipment_type = models.CharField(choices=type_choices, max_length=20)
    status_choices = [
        ('available', 'Available'),
        ('scheduled', 'Scheduled'),
        ('in_use', 'In Use'),
        ('in_repair', 'In Repair')
    ]
    rent_amount = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(
        upload_to='Equipment',
        max_length=300,
        default=''
    )
    status = models.CharField(choices=status_choices, max_length=20, default='available')

    def __str__(self):
        return self.name

class HouseDesign(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    style_choices = [
        ('modern', 'Modern'),
        ('traditional', 'Traditional'),
        ('contemporary', 'Contemporary'),
        ('rustic', 'Rustic')
    ]
    style = models.CharField(choices=style_choices, max_length=20)
    square_footage = models.IntegerField()
    num_bedrooms = models.IntegerField()
    num_bathrooms = models.IntegerField()
    num_floors = models.IntegerField()
    garage_choices = [
        ('none', 'None'),
        ('attached', 'Attached'),
        ('detached', 'Detached')
    ]
    garage = models.CharField(choices=garage_choices, max_length=20, default='none')
    image = models.ImageField(upload_to='house_designs/', blank=True)

    def __str__(self):
        return self.name


class EquipmentRentBooking(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(default=date.today)
    end_date = models.DateField()
    quantity = models.PositiveIntegerField()
    total_cost = models.DecimalField(max_digits=8, decimal_places=2)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} - {self.equipment.name} - {self.start_date} to {self.end_date}'

class ProjectAssignment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    engineer = models.ForeignKey(SiteEngineer, on_delete=models.CASCADE)
    assigned_date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return f'{self.engineer.user.username} - {self.project.name}'

customer/models.py
from django.db import models
from accounts.models import User
from datetime import datetime

# Create your models here.

class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    budget = models.DecimalField(max_digits=8, decimal_places=2)
    status_choices = [
        ('not_started', 'Not Started'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed')
    ]
    status = models.CharField(choices=status_choices, max_length=20)
    customer = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Complaint(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    description = models.TextField()
    date_filed = models.DateTimeField(auto_now_add=True)
    is_resolved = models.BooleanField(default=False)
    date_resolved = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.subject} ({self.customer.name})'

customer/forms.py
from django import forms
from .models import *
from admin.models import EquipmentRentBooking



class DateInput(forms.DateInput):
    input_type = 'date'

class ProjectForm(forms.ModelForm):
    """Form definition for Project."""

    class Meta:
        """Meta definition for Projectform."""

        model = Project
        exclude = ['customer', 'status']
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput()
        }

class ComplaintForm(forms.ModelForm):
    """Form definition for Complaint."""

    class Meta:
        """Meta definition for Complaintform."""

        model = Complaint
        exclude = ['customer', 'is_resolved', 'date_resolved']


class EquipmentRentBookingForm(forms.ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = EquipmentRentBooking
        exclude = ('equipment', 'is_approved', 'user')
        widgets = {
            'start_date': DateInput(),
            'end_date': DateInput()
        }



customer/views.py
from django.shortcuts import render, redirect
from .forms import *
from admin.models import ProjectAssignment, HouseDesign
from admin.models import Equipment, EquipmentRentBooking
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
    equipments = Equipment.objects.filter(status='available')
    return render(request, 'customer/index.html', {'equipments': equipments})

def housedesigns(request):
    housedesigns = HouseDesign.objects.all()
    return render(request, 'customer/house.html', {'housedesigns': housedesigns})

def housedesignsdetails(request, id):
    design = HouseDesign.objects.get(pk=id)
    return render(request, 'customer/more.html', {'design': design})


@login_required
def booknow(request, id):
    equipment = Equipment.objects.get(pk=id)
    if request.method == 'POST':
        form = EquipmentRentBookingForm(data=request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.equipment = equipment
            obj.user = request.user
            obj.save()
            return redirect('custome_index')
    else:
        form = EquipmentRentBookingForm()
    return render(request, 'customer/booking.html', {'form': form, 'equipment': equipment})

@login_required
def my_orders(request):
    orders = EquipmentRentBooking.objects.filter(user=request.user)
    return render(request, 'customer/orders.html', {'orders': orders})

@login_required
def delete_order(request, id):
    EquipmentRentBooking.objects.get(pk=id).delete()
    return redirect('custome_my_orders')

@login_required
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.customer = request.user
            obj.status = 'not_started'
            obj.save()
            return redirect('custome_add_project')
    else:
        form = ProjectForm()
    return render(request, 'customer/create_project.html', {'form': form})

@login_required
def manage_project(request):
    projects = Project.objects.filter(customer=request.user)
    return render(request, 'customer/manage_project.html', {'projects': projects})

@login_required
def edit_project(request, id):
    project = Project.objects.get(pk=id)
    if request.method == 'POST':
        form = ProjectForm(data = request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('custome_manage_project')
    else:
        form = ProjectForm(instance=project)
    return render(request, 'customer/edit_project.html', {'form': form})

@login_required
def delete_project(request, id):
    Project.objects.get(pk=id).delete()
    return redirect('custome_manage_project')

@login_required
def add_compalints(request):
    if request.method == 'POST':
        form = ComplaintForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.customer = request.user
            obj.save()
            return redirect('custome_add_compalints')
    else:
        form = ComplaintForm()
    return render(request, 'customer/add_compalints.html', {'form': form})


    

customer/templates/customer/shared/base.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title>Construction - Free HTML Bootstrap Template</title>
        <!-- Mobile Specific Meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <!-- Custom Fonts -->
        <link rel="stylesheet" href="{% static 'custom-font/fonts.css' %}" />
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="css/font-awesome.min.css" />
        <!-- Bootsnav -->
        <link rel="stylesheet" href="{% static 'css/bootsnav.css' %}">
        <!-- Fancybox -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fancybox.css' %}" media="screen" />	
        <!-- Custom stylesheet -->
        <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>

        <!-- Preloader -->

        <div id="loading">
            <div id="loading-center">
                <div id="loading-center-absolute">
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                    <div class="object"></div>
                </div>
            </div>
        </div>

        <!--End off Preloader -->

        {% include 'customer/shared/nav.html' %}


        <section id="home" class="home">
            
            {% block main %}
                
            {% endblock main %}
                
        </section>

        <!-- Footer -->
        <footer>
            <!-- Footer top -->
            <div class="container footer_top">
                <div class="row">
                    <div class="col-lg-4 col-sm-7">
                        <div class="footer_item">
                            <h4>About Company</h4>
                            <img class="logo" src="static/images/logoproj.png" alt="Construction" />
                            <p>We are here to help you to get equipments for the construction of your building. We also provide best housedesign of your choice </p>

                            <ul class="list-inline footer_social_icon">
                                <li><a href=""><span class="fa fa-facebook"></span></a></li>
                                <li><a href=""><span class="fa fa-twitter"></span></a></li>
                                <li><a href=""><span class="fa fa-youtube"></span></a></li>
                                <li><a href=""><span class="fa fa-google-plus"></span></a></li>
                                <li><a href=""><span class="fa fa-linkedin"></span></a></li>
                            </ul>
                        </div>
                    </div>
                    
                    
                    <div class="col-lg-3 col-sm-5">
                        <div class="footer_item">
                            <h4>Contact us</h4>
                            <ul class="list-unstyled footer_contact">
                                <li><a href=""><span class="fa fa-map-marker"></span>ADDRESS:Make Aim Company kochi,eranakulam</a></li>
                                <li><a href=""><span class="fa fa-envelope"></span> EMAIL: makeaimcompany@gmail.com</a></li>
                                <li><a href=""><span class="fa fa-mobile"></span><p>+91 9764246674 <br />+91 8664342323</p></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!-- Footer top end -->

            <!-- Footer bottom -->
            <div class="footer_bottom text-center">
                <p class="wow fadeInRight">
                    Made with 
                    <i class="fa fa-heart"></i>
                    by 
                    <a target="_blank" href="http://bootstrapthemes.co">Bootstrap Themes</a> 
                    2016. All Rights Reserved
                </p>
            </div><!-- Footer bottom end -->
        </footer><!-- Footer end -->

        <!-- JavaScript -->
        <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- Bootsnav js -->
        <script src="{% static 'js/bootsnav.js' %}"></script>

        <!-- JS Implementing Plugins -->
        <script src="{% static 'js/isotope.js' %}"></script>
        <script src="{% static 'js/isotope-active.js' %}"></script>
        <script src="{% static 'js/jquery.fancybox.js' %}"></script>

        <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>
        <script>
            $(function(){
                $('input').addClass('form-control');
                $('textarea').addClass('form-control');
                $('#id_quantity').change(function(){
                    let amount = parseFloat($('#rent').val())*parseInt($(this).val());
                    var days = daydiff($('#id_start_date').val(), $('#id_end_date').val())
                    $('#id_total_cost').val(amount*days)
                })
            })


            function daydiff(d1, d2){
                var sd = new Date(d1);
                var ed = new Date(d2);

                var milli = sd.getTime() - ed.getTime()

                var days = milli / (1000*3600*24);

                return Math.round(Math.abs(days));
            }
        </script>
    </body>	
</html>	

customer/templates/customer/shared/nav.html
<!-- Header -->
<header>
    <!-- Navbar -->
    <nav class="navbar bootsnav">
        <!-- Top Search -->
        <div class="top-search">
            <div class="container">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
                </div>
            </div>
        </div>

        <div class="container">
            <!-- Atribute Navigation -->
            <div class="attr-nav">
                <ul>
                    <li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
                </ul>
            </div>
            <!-- Header Navigation -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href=""><img class="logo" src="static/images/logoproj.png" alt="" ></a>
            </div>
            <!-- Navigation -->
            <div class="collapse navbar-collapse" id="navbar-menu">
                <ul class="nav navbar-nav menu">
                    <li><a href="{% url 'custome_index' %}">Home</a></li>                 
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Construction
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'custome_add_project' %}">Add Projects</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'custome_manage_project' %}">Manage Projects</a>
                        </div>
                      </li>
                    <li><a href="{% url 'custome_add_compalints' %}">Complaint</a></li>
                    <li><a href="{% url 'custome_my_orders' %}">My Orders</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Accounts
                        </a>
                        
                        {% if user.is_authenticated %}
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'accounts_profile' %}">Edit Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts_change_password' %}">Change Password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts_logout' %}">Logout</a>
                        </div>
                        {% else %}
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'accounts_signin' %}">Login</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts_register' %}">User Register</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts_engineer_register' %}">Site Engineer Register</a>
                          </div>
                        {% endif %}
                            
                      </li>
                </ul>
            </div>
        </div>   
    </nav><!-- Navbar end -->
</header><!-- Header end -->

